# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 28, 21, 30, 26, 983912, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
