# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 15:23
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('job_board', '0002_job_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_after', models.SmallIntegerField(default=30)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Please leave empty if 100% virtual', null=True, on_delete=django.db.models.deletion.CASCADE, to='job_board.Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(help_text='Please leave empty if none', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_info',
            field=models.TextField(help_text="What's the best way to apply for this job? <a href='http://daringfireball.net/projects/markdown/syntax'>Markdown</a> accepted"),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Select if you're hiring within a specific country", null=True, on_delete=django.db.models.deletion.CASCADE, to='job_board.Country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text="Feel free to use <a href='http://daringfireball.net/projects/markdown/syntax'>Markdown</a> to format description"),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(help_text='This is the address we will use to contact you; it will be not be visible on the public site', max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.TextField(blank=True, help_text='Specify timezone requirements or other location-related details'),
        ),
    ]
