# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_auto_20160712_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='admin_email',
            field=models.EmailField(default='admin@site', max_length=254),
        ),
    ]
