# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0006_siteconfig_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, help_text='Please leave empty if none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='remote',
            field=models.BooleanField(default=False, help_text='Select if this job board is for remote jobs only'),
        ),
    ]
