# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0007_auto_20160928_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, help_text='Specify timezone requirements or other location-related details', max_length=100, null=True),
        ),
    ]
