# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0008_auto_20161001_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
