# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0011_auto_20161118_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='google_analytics',
            field=models.CharField(blank=True, help_text='Google Analytics Tracking ID', max_length=20),
        ),
    ]
