# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0012_siteconfig_google_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='twitter',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
