# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0013_siteconfig_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='twitter',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_access_token_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_consumer_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_consumer_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_user',
            field=models.CharField(blank=True, help_text="Your site's Twitter username, fill in to have a Follow icon appear on select pages", max_length=15),
        ),
    ]
