# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0014_auto_20161123_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
