# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0015_auto_20161127_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price to charge for posting a job, set to 0 to disable charging', max_digits=5),
        ),
    ]
