# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0016_siteconfig_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
