# Generated by Django 2.2.11 on 2020-03-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0019_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Please leave empty if 100% virtual', null=True, on_delete=django.db.models.deletion.PROTECT, to='job_board.Country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_board.Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_board.Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Select if you're hiring within a specific country", null=True, on_delete=django.db.models.deletion.PROTECT, to='job_board.Country'),
        ),
    ]
